### ISSUE TITLE
White flickering  (Blinking) with autoplay and loop

### ISSUE THREAD

**Issue by sstedik** [r0b0t3d/react-native-carousel#25]
When the last slide is scrolled, there is a white flickering on android
(the **autoplay** and **loop** props are set to true)

Bug reproduced by example which in repository
Version 3.4.2
Android

I tried to add removeClippedSubviews={false) but then there is an effect of the element appearing on the right

**Comment by r0b0t3d** [comment]
Hi @sstedik this issue is resolved in [v3.4.4](https://github.com/r0b0t3d/react-native-carousel/releases/tag/v3.4.4)
